services:
  influxdb:
    image: influxdb:2.7.11
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      net:
        ipv4_address: 192.68.0.21

  adaptor:
    build: adaptor
    volumes:
      - adaptor-storage:/var/lib/adaptor:rw
    links:
      - influxdb
    depends_on:
      - influxdb
    ports:
      - 8080:8080
    networks:
      net:
        ipv4_address: 192.68.0.25

  registry:
    build: registry
    volumes:
      - registry-storage:/var/lib/registry:rw
    ports:
      - 8081:8081
    restart: always
    networks:
      net:
        ipv4_address: 192.68.0.24

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  flutter_web:
    build:
      context: ./web-release       
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: flutter_web_container

  pub_simulator:
    build: pubsimulator
    depends_on:
      - adaptor
    restart: always
    networks:
      net:
        ipv4_address: 192.68.0.26

  capetti:
    build:
      context: ./capetti_devices
      dockerfile: Dockerfile
    depends_on:
      - adaptor
    restart: always
    networks:
      net:
        ipv4_address: 192.68.0.27

  netatmo:
    build:
      context: ./netatmo_devices
      dockerfile: Dockerfile.dockerfile
    depends_on:
      - registry
      - adaptor
    restart: always
    networks:
      net:
        ipv4_address: 192.68.0.28
  
  plot_service:
    build: ./technical_graphs  
    depends_on:
      - adaptor
    ports:
      - 9090:9090
    networks:
      net:
        ipv4_address: 192.68.0.29

  kpi-system:
    build: ./kpis_and_suggestions
    depends_on:
      - registry
      - adaptor
    networks:
      - net
      #net:
        #ipv4_address: 192.68.0.30
    environment:
      PYTHONUNBUFFERED: "1"
    restart: on-failure

  mqtt_aggregator:
    build: ./mqtt_aggregator
    depends_on:
      - registry
    restart: always
    ports:
      - 8085:8085
    networks:
      net:
        ipv4_address: 192.68.0.31



volumes:
  influxdb-storage:
  adaptor-storage:
  registry-storage:

networks:
  net:
    ipam: 
      driver: default
      config:
        - subnet: "192.68.0.0/24"